### ISSUE TITLE
制作登录窗口的设置界面

### ISSUE THREAD

**Issue by ohto-ai** [NOPornLivePlatform/LivePlatform#3]
![image](https://user-images.githubusercontent.com/46275725/94354128-bec5b380-00aa-11eb-8e33-e67e266ec407.png)
就是这个

**Comment by ohto-ai** [comment]
需要添加的设置功能  
- 服务器地址
- 访问官网

**Comment by thatboy-echo** [comment]
需要添加的设置功能

-   退出登录
-   个人空间[链接到网页]  
-   摄像头设置
    -   选择摄像头
    -   摄像头预览
-   麦克风设置
    -   选择麦克风
    -   麦克风试听

**Comment by ohto-ai** [comment]
已完成 https://github.com/NOPornLivePlatform/LivePlatform/commit/18ff1c3cfc83c2a4fa198466f2da73fdb4c18aed
